### ISSUE TITLE
Yokogawa GS200 C/C++ support

### ISSUE THREAD

**Issue by surjitsinh** [lab-measurement/lab-measurement#1]
hello,

i want to know yokogawa GS200 GPIB only works with perl/linux or it can also communication using c program. please help.

**Comment by Christian-H-B** [comment]
Hello surjitsinh,
if I understand you correctly, you want to use the YokogawaGS200 instrument library, provided within Lab::Measurement in your C/C++ code. This is not possible (or maybe it is, but it's for sure not a good idea). 
However, generally it is quite easy to communicate with a device, supporting GPIB and other connectors, using the VISA libraries by National Instruments (https://www.ni.com/visa/). Maybe this document by Agilent can help you start with it: http://cp.literature.agilent.com/litweb/pdf/E2090-90040.pdf
Of course you can study our YokogawaGS200 library and build something similar in C or at least you can find the device commands in the code, if you do not want to look it up in the manual.

Best,
Christian

**Comment by surjitsinh** [comment]
Hello,

Thank you for your support, I am trying to use tmctl.lib in linux (Qt) but
it shows error that some commands works with windows API, can you provide
linux library for your device. Thank you

Best regards,
Surjit
