### ISSUE TITLE
Tests fail on FreeBSD (gnuplot issue?)

### ISSUE THREAD

**Issue by akhuettel** [lab-measurement/Lab-Measurement#12]
http://www.cpantesters.org/cpan/report/8771e728-710b-11e7-a270-8a4a2e50ec7f

**Comment by amba** [comment]
```
PDL::Graphics::Gnuplot: your gnuplot appears not to support the terminal 'dumb'.
        dumb: dumb terminal (ASCII output) [not in reported list from gnuplot]

You can use the 'terminfo' method for a list of available terminals.

 at /usr/perl5.20.2p/lib/site_perl/5.20.2/PDL/Graphics/Gnuplot.pm line 2287.
	PDL::Graphics::Gnuplot::output(undef, undef) called at /usr/perl5.20.2p/lib/site_perl/5.20.2/PDL/Graphics/Gnuplot.pm line 2140
	PDL::Graphics::Gnuplot::new("PDL::Graphics::Gnuplot", "dumb") called at t/Moose/Plot.t line 30
```

The 'dumb' terminal is required for the tests (Also true for the P::G::G tests). Don't think we can do anything here.

**Comment by amba** [comment]
@eserte: Would be interesting to know what gnuplot version you run on that test box. The 'dumb' terminal does not have any extra dependencies and is usually built with the default gnuplot configuration.

Thanks in advance :)

**Comment by eserte** [comment]
I don't think it's a gnuplot issue. In http://matrix.cpantesters.org/?dist=Lab-Measurement%203.554;os=freebsd;reports=1#sl=2,1 all the reports by me and osvers=10.1+10.3 are from the same box, with the same gnuplot binary.

Right now I generated a pass report with this perl on the same system, by forcing PDL 2.018 instead of 2.017 as its dependency.

**Comment by amba** [comment]
Thanks for the hint.
Strange thing is that we have both fails and passes with the version combination

    PDL                                 2.007      2.017   
    PDL::Core                              0      2.017   
    PDL::Graphics::Gnuplot        0      2.009

**Comment by eserte** [comment]
You're right --- it even passes for that perl with PDL 2.017.

Maybe a rare race condition? But I ran 200x ``perl5.20.2 -MPDL::Graphics::Gnuplot -e 'warn PDL::Graphics::Gnuplot->new("dumb")'`` (which seemed to fail then), without any failures.

**Comment by amba** [comment]
@akhuettel - Not reproducible... Close it?
