### ISSUE TITLE
old versions

### ISSUE THREAD

**Issue by chorny** [lab-measurement/Lab-Measurement#15]
Please remove AKHUETTEL/Lab-Measurement-3.553.tar.gz (and possibly earlier) from CPAN. This version is still indexed (probably because in newer versions some module was removed) and is tested by cpantesters smokers causing problems because it hangs.
CPAN mirrors disk space will be freed too.
You can check for other indexed old versions here: http://cpanold.chorny.net/?a=AKHUETTEL

**Comment by akhuettel** [comment]
Scheduled for deletion (due at Fri, 01 Dec 2017 18:33:36 GMT)

Thanks!
