### ISSUE TITLE
Handling of non-T&M USB instruments?

### ISSUE THREAD

**Issue by akhuettel** [lab-measurement/Lab-Measurement#22]
We should think at least in principle about how we want to handle non-T&M USB instruments (i.e. different USB device classes). Most relevant are probably

* simulated serial port
* camera?

**Comment by amba** [comment]
Regarding simulated serial port:
- On Windows one might use VISA.
- On Linux one would might build something with Device::SerialPort, like the old Lab::Bus driver.

At the moment I cannot come up with any hardware which would profit from a driver.
In AG Strunk we have not used serial port for quite some time.

I feel that for the moment the focus should be on having a reliable, well tested, and cross-platform USBTMC ;).
