### ISSUE TITLE
Port remaining instruments to Moose

### ISSUE THREAD

**Issue by akhuettel** [lab-measurement/Lab-Measurement#23]
Let's track here what isn't ported to Moose yet. On a first glance I see:

* Andeen Hagerling AH2700A capacitance bridge
* HP / Agilent 34420A nanovoltmeter (SCPI, should be trivial)
* Cryogenic SMS magnet power supply
* Oxford Instruments IPS, ITC, ILM (the old devices); TLM temperature control
* Keithley 2000 multimeter, Keithley 2400 source
* Lakeshore 224, 33x, 340 temperature measurements
* Anritsu MG369xB series signal generator
* Signal Recovery 7260 / 7265 Lock-in Amplifier
* Various step motors
* Tektronix TDS2024B digital oscilloscope
* ABB TRMC2 temperature controller

**Comment by amba** [comment]
Actually all relevant hardware used in the Strunk labs is ported to Moose.
Additionally we support the Keithley SMUs.

One exception are the byzantine stepper motor drivers, where it might be wise to write minimal Moose wrappers around those.
 
Closing this ticket for now. We can still open issues for individual hardware when needed.
