### ISSUE TITLE
missing Moose driver: HP34420A nanovoltmeter

### ISSUE THREAD

**Issue by akhuettel** [lab-measurement/Lab-Measurement#34]
The driver for the HP34420A nanovoltmeter needs porting to Moose.

(We may already be covered here with existing drivers for similar equipment, needs review.)

https://www.keysight.com/de/de/product/34420A/micro-ohm-meter.html

**Comment by amba** [comment]
There is already a driver: Lab::Moose::Instrument::HP34420A
