### ISSUE TITLE
gnuplot 5 for windows delivers gnuplot.exe, not pgnuplot.exe

### ISSUE THREAD

**Issue by akhuettel** [lab-measurement/lab-measurement#4]
gnuplot 5 for windows delivers gnuplot.exe, not pgnuplot.exe ...

We need to
- either check first for pgnuplot.exe then gnuplot.exe
- or make the binary name configurable in a central location

**Comment by akhuettel** [comment]
@amba I assume this is eventually fixed by using the PDL code?

**Comment by amba** [comment]
Yeah, PDL::Graphics::Gnuplot (actually Alien::Gnuplot) searches for gnuplot.exe by default and can be customized with the GNUPLOT_BINARY environment variable.

In my [recent tests](https://github.com/drzowie/PDL-Graphics-Gnuplot/issues/57) all windows releases of gnuplot down to 4.6.0, released in 2012, deliver gnuplot.exe not pgnuplot.exe.

So for the XPRESS code, maybe we should just change it to gnuplot.exe and make a note in the installation instructions. I don't think that gnuplot versions <4.6.0 are still relevant.
